### ISSUE TITLE
Write code for evaluating submissions

### ISSUE THREAD

**Issue by ethanwhite** [NIST-NEON-DSE/NIST-DSE-organization#26]
- [ ] Segmentation
- [ ] Alignment
- [ ] Classification

**Comment by ethanwhite** [comment]
I believe @dihong's last update was that the Segmentation section was complete, but not the other two. If either @daisyw or @dihong can check off any check boxes above that are complete and leave an update on the status here that would be great.

**Comment by dihong** [comment]
Hi Ethan,


The segmentation task has been completed (both baseline implementation and analytic report), and I am currently working on the other two tasks with another student (Sudeep). Sudeep is responsible for presenting analytic results of the report for the other two tasks.


Thanks,

Dihong

________________________________
