### ISSUE TITLE
Should we make the Alignment task unsupervised?

### ISSUE THREAD

**Issue by ethanwhite** [NIST-NEON-DSE/NIST-DSE-organization#39]
In writing about the Alignment task it is clear that the end goal is for this to be an unsupervised task:

1. Segment crowns
2. Assign a stem from the field data to a crown without any ground truth information

We have chosen (appropriately) to provide participants with the perfect version of (1), but should we give them the labels, which they won't have in a real world scenario?

**Comment by davharris** [comment]
We decided in today's meeting not to do this.
